/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is manually maintained (originally auto-generated by TanStack Router).

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as DocsCategoryIndexRouteImport } from './routes/docs.$category.index'
import { Route as DocsCategorySlugRouteImport } from './routes/docs.$category.$slug'
import { Route as AdminEditCategorySlugRouteImport } from './routes/admin.edit.$category.$slug'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategoryIndexRoute = DocsCategoryIndexRouteImport.update({
  id: '/docs/$category/',
  path: '/docs/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategorySlugRoute = DocsCategorySlugRouteImport.update({
  id: '/docs/$category/$slug',
  path: '/docs/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditCategorySlugRoute = AdminEditCategorySlugRouteImport.update({
  id: '/admin/edit/$category/$slug',
  path: '/admin/edit/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
  '/admin/edit/$category/$slug': typeof AdminEditCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/docs/$category': typeof DocsCategoryIndexRoute
  '/admin/edit/$category/$slug': typeof AdminEditCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/docs/$category/': typeof DocsCategoryIndexRoute
  '/admin/edit/$category/$slug': typeof AdminEditCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portfolio'
    | '/admin/login'
    | '/admin/'
    | '/docs/$category/$slug'
    | '/docs/$category/'
    | '/admin/edit/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portfolio'
    | '/admin/login'
    | '/admin'
    | '/docs/$category/$slug'
    | '/docs/$category'
    | '/admin/edit/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/portfolio'
    | '/admin/login'
    | '/admin/'
    | '/docs/$category/$slug'
    | '/docs/$category/'
    | '/admin/edit/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DocsCategorySlugRoute: typeof DocsCategorySlugRoute
  DocsCategoryIndexRoute: typeof DocsCategoryIndexRoute
  AdminEditCategorySlugRoute: typeof AdminEditCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/': {
      id: '/docs/$category/'
      path: '/docs/$category'
      fullPath: '/docs/$category/'
      preLoaderRoute: typeof DocsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/$slug': {
      id: '/docs/$category/$slug'
      path: '/docs/$category/$slug'
      fullPath: '/docs/$category/$slug'
      preLoaderRoute: typeof DocsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$category/$slug': {
      id: '/admin/edit/$category/$slug'
      path: '/admin/edit/$category/$slug'
      fullPath: '/admin/edit/$category/$slug'
      preLoaderRoute: typeof AdminEditCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  DocsCategorySlugRoute: DocsCategorySlugRoute,
  DocsCategoryIndexRoute: DocsCategoryIndexRoute,
  AdminEditCategorySlugRoute: AdminEditCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
